package com.scytl.multi;

import javax.enterprise.event.Observes;
import java.sql.Connection;
import java.sql.SQLException;
import java.sql.Statement;

public class CreateDatabaseSchemaListener {

    public void createSchema(@Observes CreatedDataSourceEvent event) {
        try {
            Connection conn = event.getDataSource().getConnection();
            Statement st = conn.createStatement();
            st.executeUpdate("create table Person (id bigint generated by default as identity (start with 1), name varchar(255), primary key (id));");
            st.close();
        } catch (SQLException e) {
            throw new IllegalArgumentException(e);
        }

    }

}
